### PR TITLE
Update ColorService.js

### LINKED ISSUE #58: Add more colors to ColorService
Currently there are 7 colors for schedule blocks in `ColorService`. Now if anyone takes more than 7 classes that's kind of alarming, but nevertheless it doesn't hurt to have more colors.

### PR DESCRIPTION
**Pull request by JaBeast13**
Color Service

> Closes #58

Added 5 more colors to ColorService.js, teal, maroon, pink, dark blue, and dark green.

**Test Procedure**

Add classes to the course scheduler, and you will be able to see the new colors added.

**Photos**

updated_colors

**Additional Info**

Do not take 36 credit hours. You will die.
-Nick King and Joshua Marion

### CODE REVIEW

**Comment by RichtXO** [comment]
That teal color makes the text hard to read for me :(

**Comment by jshom** [comment]
That red color in the middle is a little dark to have black text, perhaps we stay in the light/tan color pallette? wyt?

**Comment by JaBeast13** [comment]
[
updated_colors_2
](url)

We updated the maroon background so that the text stands out better, as well as the teal text to make it a little darker and easier to read.

**Review by keerti-sundaram — APPROVED** [review]
Looks good to me!

**Review by gizzon — APPROVED** [review]
Looks good to me! Thanks for cleaning up the code as well :)

**Pull request merged**
