### PR TITLE
Ui tweaks sortorder space optimization

### PR DESCRIPTION
**Pull request by jshom**
Screen Shot 2020-03-15 at 1 16 21 AM
Contribute to #34, need better veritical page partitioning when we are more done with functionality as it is now set to 700 px

### CODE REVIEW

**Comment by 123joshuawu** [comment]
Maybe good to remove the sorting of results from YacsService and leave that to the backend? Can do the same for Departments, Subsemesters, and possibly CourseSections and CourseSessions?

**Comment by jshom** [comment]
Agree yep let me double check

**Comment by jshom** [comment]
ah yep, forgot to commit that after merge. shifting sorting to db in a sec, 2 min.

**Comment by CoreyBuckley** [comment]
I will be committing some minor changes:

- Don't need overflow-x to always be scroll.
- Make `height` max-height instead so when I use mobile view I don't have a large chunk of empty space if I were to filter to one course.

**Pull request merged**
