### PR TITLE
Color blind assist

### PR DESCRIPTION
**Pull request by NickKing24**
**Issue**

> closes Feature Request — Color Blindness #374

**UI Modifications**

Added a new color blind friendly color palette to ColorService.js that works with protanopia (red-blind), deuteranopia (green-blind), and tritanopia (blue-blind) and added the ability to toggle between the existing and new palette. Also changed the course link color to black for it to work with the new palette.

**Test Procedure**

> 1. Add courses to the scheduler
> 2. Click the color blind assistance toggle located above the export data dropdown

**Photos**

Toggle
image

Default colors
image

New color blind friendly colors
image

Simulated color blindness pictures

Protanopia
image

Deuteranopia
image

Tritanopia
image

**Additional Info**

Used https://www.color-blindness.com/coblis-color-blindness-simulator/ to test the new palette and get the simulated color blindness pictures. This pull request assumes Update ColorService.js #421 has been merged.

### CODE REVIEW

**Comment by gizzon** [comment]
LGTM! This is great

**Review by gizzon — APPROVED** [review]
LGTM! This is great

**Review by RichtXO — APPROVED** [review]
LGTM! NIce one

**Comment by RichtXO** [comment]
@NickKing24 Just fix the conflicting `ColorService.js`, and you're clear to merge.

**Pull request merged**
