### PR TITLE
Revert dark mode badge overrides

### LINKED ISSUE #354: UX Bug — Badges in dark mode
**Describe the bug**
The number of seats badge feature uses different color backgrounds to convey meaning, however in dark mode, the colored backgrounds are all black

**To Reproduce**
1. Go to course scheduler page
2. Toggle on dark mode

**Expected behavior**
Green badges should stay green, etc.

**Screenshots**
Screen Shot 2020-11-22 at 3 14 58 PM
Screen Shot 2020-11-22 at 3 14 07 PM
Screen Shot 2020-11-22 at 3 13 41 PM

### PR DESCRIPTION
**Pull request by 123joshuawu**
**Issue**

Closes #354 

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**

1. Go to scheduling page
2. Toggle on dark mode

**Photos**
Screen Shot 2020-11-22 at 3 13 41 PM
Screen Shot 2020-11-22 at 3 11 31 PM

### CODE REVIEW

**Review by nick-lennox — APPROVED** [review]

**Comment by marchdan** [comment]
@123joshuawu I think this change caused the counter on selected courses to not have a dark background (look at your screen shots)

**Comment by jshom** [comment]
@123joshuawu 
Screen Shot 2020-11-22 at 6 32 26 PM
Can you handle confirming the dark mode style of these lines to the other `<hr>s` on the page.

<hr>

Also, not sure if you wanna handle this in this issue or another, but maxing out this height and doing the y-overflow: scroll like the search tab, otherwise the export and credit counts are off the screen essentially.
Screen Shot 2020-11-22 at 6 33 33 PM

**Comment by 123joshuawu** [comment]
@marchdan yeahh, that looks ok to me? Or should we revert it to the previous light grey text on black background?

**Comment by marchdan** [comment]
> @marchdan yeahh, that looks ok to me? Or should we revert it to the previous light grey text on black background?

I think the previous, it looks like a weird text box to me instead of a count.

**Comment by 123joshuawu** [comment]
@jshom fixed both

**Review by marchdan — APPROVED** [review]

**Review by jshom — APPROVED** [review]

**Pull request merged**
