### PR TITLE
ui tweaks, still needs more for beta release, deadlinks in footer

### PR DESCRIPTION
**Pull request by jshom**
We will be releasing beta soon, decided to add some design tweaks so we can read for v0
Screen Shot 2020-03-29 at 6 29 17 PM

### CODE REVIEW

**Comment by 123joshuawu** [comment]
Looks good to me, also just letting you know that `yacs.n/package-lock.json` got deleted

**Comment by CoreyBuckley** [comment]
Footer looks good! Minor thing is I think it would be nice if you could move the "export" button to be above the schedule. For my screen size, I have to scroll down in order to see the button. Feel like it would make more sense to have be visible "above the fold".

**Comment by CoreyBuckley** [comment]
kinda like this

image

or this

image

what you think?

**Comment by 123joshuawu** [comment]
Maybe we could move it with selectedcourses?

**Comment by jshom** [comment]
@123joshuawu ye, I was thinking we could make the sub semester tabs just like the course search and selected courses. What you think?

Regarding the position of the export to ics, lets leave it as is. Once we have more export options I think the design choice will be easier to make.

**Pull request merged**
