### PR TITLE
add SelectedCoursesCookie controller to persist schedules for anonymous users

### LINKED ISSUE #210: Scheduling - Persist selected courses in cookies
**Job**
When I am not logged it, I don't want to lose a schedule I was putting together

**Describe a possible solution**
Cookie a map of selected courses to semesters, so that persisting schedules on the same device does not require logging in.

**Context**
Currently, for someone to see their schedule after a refresh is only through creating an profile, most students will most likely not create an account, so make it easy for them to transition from previous to new yacs.

### PR DESCRIPTION
**Pull request by 123joshuawu**
**Issue**

Closes #210 

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**
Persist in reloads
1. Load CourseScheduler page
2. Select a course
3. Reload the page
    1. The previous course should be selected and section should be selected
4. Switch to different semester and back
    1. The previous course should be selected and section should be selected

**Photos**

N/A

**Additional Info**

N/A

### CODE REVIEW

**Comment by 123joshuawu** [comment]
Theres a bug with removing courses, fixing

**Comment by marchdan** [comment]
@123joshuawu there are some inconsistencies in console logging between saving logged in versus logged out. Not huge, but it would be nice if the logs looked the same logged in versus logged out for consistency

**Comment by 123joshuawu** [comment]
@marchdan hmm not sure what you mean, can u explain a little more? And I think I took out all the debug logs from this code

**Comment by jshom** [comment]
Agree, better no debug logs in prod. Makes it harder to debug future features

**Review by jshom — APPROVED** [review]
This is awesome, lgtm!

**Comment by jshom** [comment]
What u think about new continuation issue for on sign up (new account), we save existing course selections. wyt?

**Comment by marchdan** [comment]
@123joshuawu there are a bunch of console.log calls when courses/sections are added or removed. There is different data logged depending if someone is logged in or not. I have no issue with removing them, just think if they are going to be there they should be consistent

**Comment by marchdan** [comment]
@jshom I think that would make sense

**Comment by 123joshuawu** [comment]
@marchdan off the top of my head, I know I left some logging statements in the `Schedule` controller class, some for schedule conflicts, but all of those should be the same regardless of whether you're logged in or not. Which logs are you referring to?

**Comment by marchdan** [comment]
https://github.com/YACS-RCOS/yacs.n/blob/f236137b0001a80653311f87d53a7e6be4cfda15/src/web/src/pages/CourseScheduler.vue#L347-L360

https://github.com/YACS-RCOS/yacs.n/blob/f236137b0001a80653311f87d53a7e6be4cfda15/src/web/src/pages/CourseScheduler.vue#L374-L387

https://github.com/YACS-RCOS/yacs.n/blob/f236137b0001a80653311f87d53a7e6be4cfda15/src/web/src/pages/CourseScheduler.vue#L417-L430

https://github.com/YACS-RCOS/yacs.n/blob/f236137b0001a80653311f87d53a7e6be4cfda15/src/web/src/pages/CourseScheduler.vue#L443-L456

@123joshuawu

**Comment by 123joshuawu** [comment]
@marchdan ohh I see what you mean. We can probably phase them out? Next time I work on the schedulers I'll be removing those logs as well

**Comment by marchdan** [comment]
@123joshuawu That works. I am the one that added them and I assume there is a reason we left them in, but I couldn't tell you what they were

**Review by marchdan — APPROVED** [review]
Yay cookies!

**Comment by marchdan** [comment]
> What u think about new continuation issue for on sign up (new account), we save existing course selections. wyt?

@123joshuawu @jshom Is this something we were including in this PR or a future feature request?

**Comment by jshom** [comment]
> > What u think about new continuation issue for on sign up (new account), we save existing course selections. wyt?
> 
> 
> 
> @123joshuawu @jshom Is this something we were including in this PR or a future feature request?

New issue, gonna make it after this gets merged in.

**Pull request merged**
