### PR TITLE
Remove pr-cd workflows

### PR DESCRIPTION
**Pull request by 123joshuawu**

### CODE REVIEW

**Comment by RichtXO** [comment]
Do we really want to fix this? lol

**Comment by 123joshuawu** [comment]
either we fix it or take it out. It's failing all our checks

**Comment by RichtXO** [comment]
I think taking out would be better, unless Jacob wants to meet us sometime in the foreseeable future :)

**Review by RichtXO — APPROVED** [review]
We still gonna pay Jacob a visit :)

**Pull request merged**
