### PR TITLE
Fix weird mobile flex bug in selected courses 

### LINKED ISSUE #306: Bug — No selected courses on mobile
**Describe the bug**
Selected courses does not show any courses on mobile

**To Reproduce**
> 1. Open YACS prod on mobile
> 2. Select a couple courses
> 3. Go to the "Selected courses" tab. Try and look at the sections of the courses you have selected

**Expected behavior**
See the courses that are present on the schedule and their sections.

**Screenshots**
image

image

**Additional context**
This was done not logged in.

### PR DESCRIPTION
**Pull request by 123joshuawu**
**Issue**

Closes #306 

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**

1. Use mobile
2. Go to schedule page
3. Add a course
4. Click on SelectedCourses tab
5. Pues, ¿puedes verlo?

**Photos**

Screen Shot 2020-11-20 at 4 32 48 PM
Screen Shot 2020-11-20 at 4 32 30 PM

### CODE REVIEW

**Comment by marchdan** [comment]
@123joshuawu can you look at #306 while you're at it?

**Comment by 123joshuawu** [comment]
@marchdan I think I just did xd

**Comment by marchdan** [comment]
> @marchdan I think I just did xd

I high key didn't read the part where it said "Closes 306" 😂😂

**Comment by marchdan** [comment]
@123joshuawu Looks good to me. Only question is, should they be collapsed by default on mobile?

**Comment by 123joshuawu** [comment]
@marchdan i think the whole design needs to be fixed for mobile, and its probably better for now that users can see which section is selected?

**Review by marchdan — APPROVED** [review]
"That was easy"

**Review by IkeLyons — APPROVED** [review]

**Pull request merged**
