### PR TITLE
Reorganize compose files and add support for development with docker

### PR DESCRIPTION
**Pull request by 123joshuawu**
Reorganized compose files into three separate files
Their responsibilities are outlined below

`docker-compose.yml`
defines container names
build containers
establishes startup order

`docker-compose.development.yml`
expose all ports for all services to allow access
bind mount source volumes for api and web
add named volumes for web node_modules and db data
override container entry points
add development nginx to proxy webpack-dev-server sockjs messages
development environment variables

`docker-compose.production.yml`
only expose nginx 80, all other services private
production environment variables

Edited scripts to reflect above changes:
`start.sh` and `stop.sh` for starting/stopping production deployment
*Note: production starts and detaches from containers while development starts and attaches*
`startdev.sh` and `stopdev.sh` for starting/stopping development deployment
`builddev.sh` for rebuilding development containers

### CODE REVIEW

**Comment by bobmayuze** [comment]
It'd be great if u could add documentation on how to strat dev on terminal

**Comment by 123joshuawu** [comment]
Prod compose only exposes port 80 and I also changed the deploy op to use the prod compose. I can add a staging compose for prod env var and exposed ports if we want access to other ports

**Comment by jshom** [comment]
*NOTE: I added a bit of docs to the ./scripts folder*

Getting the error in the logs when trying to deploy on PR deploy. Can you debug @123joshuawu.
See: http://50.116.60.54:3000/info.txt
```
[91m-  Building for production...
[0m ERROR  Failed to compile with 1 errors11:43:53 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /app/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /app/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /app/node_modules/@babel/preset-env/lib/index.js
- /app/node_modules/@vue/babel-preset-app/index.js
- /app/node_modules/@vue/cli-plugin-babel/preset.js
- /app/node_modules/@babel/core/lib/config/files/plugins.js
- /app/node_modules/@babel/core/lib/config/files/index.js
- /app/node_modules/@babel/core/lib/index.js
- /app/node_modules/@vue/cli-plugin-babel/index.js
- /app/node_modules/@vue/cli-service/lib/Service.js
- /app/node_modules/@vue/cli-service/bin/vue-cli-service.js (While processing: "/app/node_modules/@vue/cli-plugin-babel/preset.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)

 @ multi ./src/main.js

[91m ERROR  Build failed with errors.
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m [0m[91mcode[0m[91m ELIFECYCLE
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m [0m[91merrno[0m[91m 1
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m yacs-web@0.1.0 build: `vue-cli-service build`
[0m[91mnpm[0m[91m [0m[91mERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yacs-web@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m A complete log of this run can be found in:
[0m[91mnpm[0m[91m [0m[91mERR![0m[91m     /root/.npm/_logs/2020-04-14T23_43_54_068Z-debug.log
[0m
```

**Comment by 123joshuawu** [comment]
Can't reproduce this so I'm just gonna `npm update` and see if that fixes it

**Pull request merged**
