### PR TITLE
Footer responsive bug fixes

### LINKED ISSUE #236: UX Bug — Responsive Footer
**Job**
Make `Footer` responsive

This is what it looks like on mobile:
Screen Shot 2020-10-14 at 10 22 39 PM

**Describe a possible solution**
Use breakpoints to only use two columns on smaller screen sizes

Maybe something like this
Screen Shot 2020-10-14 at 10 22 20 PM

**Context**

### LINKED ISSUE #246: UX Bug — Dark mode causes a bar of white above the footer on smaller screens
**Describe the bug**
On smaller screens (mine is 13 inches) there is a bar of white above the footer in dark mode.
(note this is one screenshot):
Screen Shot 2020-10-22 at 5 51 12 PM

With my browser set to full screen this bar goes away:
Screen Shot 2020-10-22 at 5 51 29 PM

**To Reproduce**
1. Make sure browser size is small enough
2. Go to main page or course explorer
3. Switch to dark mode
4. Observe bar of white above the header

**Expected behavior**
No bar of white while in dark mode.

### PR DESCRIPTION
**Pull request by 123joshuawu**
**Issue**

Closes #246 
Closes #236 

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**

1. Access site on mobile
2. Scroll down to footer section

**Photos**
On Mobile:
Screen Shot 2020-10-25 at 12 21 17 AM
Screen Shot 2020-10-25 at 12 20 54 AM

On Computer:
Screen Shot 2020-10-25 at 12 20 43 AM
Screen Shot 2020-10-25 at 12 20 26 AM

**Additional Info**

N/A

### CODE REVIEW

**Review by IkeLyons — APPROVED** [review]
Looks great! Also fixed some misalignment issues I was having on my smaller laptop screen so that's good. Perfect code as always ;)

**Review by marchdan — CHANGES_REQUESTED** [review]
Please resolve the file conflict and then I can approve

**Comment by marchdan** [comment]
Ummmm, the footer is no longer responsive @123joshuawu, but it was before the merge :(

**Comment by 123joshuawu** [comment]
@marchdan just checked the pr-deploy, looks like it is?

**Review by marchdan — APPROVED** [review]
Looks good to me! :)

**Comment by marchdan** [comment]
> @marchdan just checked the pr-deploy, looks like it is?

Yeah, no its good, I just big dumb XD

**Pull request merged**
