### PR TITLE
Pull Request Template 

### PR DESCRIPTION
**Pull request by jshom**
**Related Issue**

closes #113

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**

1. Create a branch
2. Commit a change to that branch
3. Push branch
4. Create Pull Request and fill in PR template

**Photos**

N/A

**Additional Info**

Note, you won't be able to test this until merged, appears to be how the github pr template works :(
Please let me know what you think should be altered/added/removed from this template.

### CODE REVIEW

**Comment by CoreyBuckley** [comment]
> Added/Altered API Routes*

I think this might be a little overkill. If there's any new routes that are important, they will probably be mentioned in the testing section. Idk, doesn't seem like a hard thing to find in the code.

I would add a description field.

I would add encouragement for attaching images of the problem and solution (if applicable).

**Comment by jshom** [comment]
> > Added/Altered API Routes*
> 
> I think this might be a little overkill. If there's any new routes that are important, they will probably be mentioned in the testing section. Idk, doesn't seem like a hard thing to find in the code.
> 

Agree with this: idea was to solve the problem of API standardization, but yes, appears this isn't the place to do it.

> I would add a description field.

Yes :)

> 
> I would add encouragement for attaching images of the problem and solution (if applicable).

Yes :)

**Comment by CoreyBuckley** [comment]
I think additional info/description should be near the top 😅

**Comment by CoreyBuckley** [comment]
> do you maybe mean a place for more info? Is this what you had in mind? If it is description of what is fixed, that should exist in the issue definition.

Additional info is fine, yes.

**Pull request merged**
