### PR TITLE
PWA Coming to YACS

### LINKED ISSUE #431: Feature Request — PWA
**Job**
Let's make YACS offline and app-friendly with PWA!

**Describe a possible solution**
Think about using the `@vue/cli-plugin-pwa` plugin, and service workers

### PR DESCRIPTION
**Pull request by RichtXO**
Got to have the YACS logo in all different dimensions.

> closes #431 

**Feature Added**
Adding PWA, users can now access YACS offline and even download the YACS app on their phone!

**Test Procedure**
Run Google's Lighthouse and see if it likes it or not.

**Additional Info**
Does anyone have Photoshop? 😀

### CODE REVIEW

**Comment by elihschiff** [comment]
https://www.pwabuilder.com/imageGenerator

This website is really helpful at generating images for a pwa, and then you should not need photoshop hopefully.

**Review by jshom — APPROVED** [review]

**Comment by jshom** [comment]
Screen Shot 2021-03-23 at 6 22 59 PM

Noticed we now get a standard Vue looking icon, but ye, looks like once you run the logo through that tool @elihschiff mentioned, should be good.

**Comment by RichtXO** [comment]
This sucks, Idk how to actually test the service worker besides pushing this to prod and praying it doesn't screw up...

**Comment by RichtXO** [comment]
Decided to try to get ssl to work on `localhost`, but making a CA with openssl is confusing af. I give up. When registration is over, I'm planning to push this and test on prod :/

**Review by IkeLyons — APPROVED** [review]

**Pull request merged**
