### PR TITLE
#370

### LINKED ISSUE #370: Feature Request — Hidden Footer
On the Landing page there is a lot going on, I feel its a little overwhelming and was thinking the footer at the bottom of each page could be hidden until an event, being scrolling extra or a secondary time after reaching the bottom of the frame. Commonly seen in Phone apps.

### PR DESCRIPTION
**Pull request by SamooMei**
**Issue**

closes #370

**Photos**

| Before     | After |
| ---      | ---       |
| Before |  after |

**Additional Info**

Changed the main-body to have a min-height of 100vh which pushes the footer down until more we scroll a bit more. 
Also made it desktop only to appease the comment above.

### CODE REVIEW

**Review by RichtXO — APPROVED** [review]
LGTM :+1:

**Comment by EthanTuttle** [comment]
Works and fixes the issue, I think this is good

**Review by EthanTuttle — APPROVED** [review]
Functionally works and fixes the issue, I approve

**Comment by RichtXO** [comment]
@SamooMei Let's do a `git rebase origin/master` first to solve the checks, then merge it!

**Pull request merged**
