### PR TITLE
Update course data in repo automatically

### LINKED ISSUE #121: Distribution — RPI : Auto Schedule Update
**Job**
As a student, I don't want to schedule with false data. Often times, the schedule often changes under our feet, a class that was once offered at 10-12 on mondays/thur is now on tuesday/friday and we need to be able to adapt to that.

**Describe a possible solution**
In a separate repo YACS-RCOS/yacs-rpi-fountain or a better name, I'm horrible at naming

- [ ] Copy parsing functionality from (yacs)/rpi-data/
- [x] Create github action that:
  - Pulls data from specified sources: i.e list https://sis.rpi.edu/reg/zs20200501.htm (for list of specified semester)
  - Sends a semesters csv to a set of YACS api's (env var's)
  - Runs every 2 hours

**Context**
While dogfooding this to schedule my classes, the class Ontologies changed its scheduling type from 12-12 M/T to 12-4 only on monday, we need to be able to pick this up on the fly. I could have missed registration for a few critical classes

**More Info**
Another intention of this is to fully extract RPI data functionality from the central repo of YACS. RPI is an instance of YACS, not RPI-YACS. This is critical for YACS's growth.

Note this should only update one semester at a time, we can expand to updating multiple semesters at a time, but it does not make much sense as the schedule does not change for last years schedule.

### PR DESCRIPTION
**Pull request by RichtXO**
**New Feature**

Now it should automatically update not only the production site but also the repository! 

> Closes #121 

**Additional Info**

Why wasn't this implemented before?????

### CODE REVIEW

**Review by 123joshuawu — COMMENTED** [review]
Looks good. But we do need to note that this will add a commit to the master branch every hour. I think we also determined that it wasn't really necessary for developers to have the most up to date hourly course data. Probably could setup a separate workflow, but probably would want to have this happen with a longer interval.

**Comment by RichtXO** [comment]
True, I do agree devs don't really need up-to-date data for testing, but it would be nice to have.
And yea, having a commit every hour wouldn't be ideal, probably every month would do.

**Comment by RichtXO** [comment]
I also realized the links to get the data don't stay active forever... maybe it's best to not have it...

**Comment by RichtXO** [comment]
@marchdan Yep! And I did make the job to update the repo once a month!

**Comment by marchdan** [comment]
Question: Does any of this automatically update the course data on prod?

**Comment by RichtXO** [comment]
@marchdan Yep! But the link may not be active in a couple of months because RPI closes them. Oh, I don't know if it would push an empty CVS file tho when the link is not active.

**Pull request closed without merging**
