### PR TITLE
Schedule Options

### LINKED ISSUE #52: Scheduling — Show all possible schedules based on selected sections
Instead of notifying users of a schedule conflict when adding a course section, indicate conflicting course sections in selected courses, then when a user selects a conflicting course section, generate all combinations of course sections that do not have a schedule conflict and their corresponding schedule. 

I'm thinking redesign of Schedule to an immutable class created using the factory design pattern.
Make Schedules lightweight and hashable to provide fast equality comparisons.

### PR DESCRIPTION
**Pull request by 123joshuawu**
**Issue**

Closes #52 

**Database Changes/Migrations**

N/A

**Test Modifications**

N/A

**Test Procedure**

N/A

**Photos**

N/A

**Additional Info**
Long queued work that really never got finished. Two main efforts.
1) Revamping state management in the front end. 
- Deprecated 'services' in favor of `vuex`'s actions. Majority of API calls revolve around centralized state to avoid over fetching. 
2) Revamping the course scheduling logic. 
- Deprecated controllers in favor of having self-contained scheduling components with their own logic. 
- Used boolean satisfiability solver to generate possible schedules from selected sections. 
- Deprecate selected courses view in favor of showing sections in course list. 

There are still a number of issues that need to be addressed before these changes are viable:
- [ ] `CourseList` render performance issues (brief investigation is showing that all `<b-collapse>` and `<router-links>` in the `CourseList` are rerendering whenever anything happens in a single `CourseListing`). It's causing my fps to drop to 0 every time I add a course and is really weird overall.
- [ ] Reworking how sections are shown in `CourseListing`. Currently the sections for each course are shown in a text format, line by line. This is 1) not very clear/appealing and 2) takes up way too much space. A more concise, visual representation is needed. Could do something similar to how Quacs shows sections which is quite visually intuitive and vertically compact, but will need to figure out how to steal their work without stealing their work.
- [ ] Adding an option for showing only selected courses. With the deprecation of the `SelectedCourses` view, the user will need a way to only show courses that they have currently selected. A simple toggle should suffice. 
- [ ] And why on earth do source maps not work???

I had wished to also get API, testing, and documentation changes in as well but the scope creep is all too real, perhaps some other time...

### CODE REVIEW

**Comment by jshom** [comment]
@123joshuawu can u handle merge conflicts, want to give this a review so we can get this merged in, thx!

**Comment by 123joshuawu** [comment]
yep sorry working on it

**Comment by RichtXO** [comment]
@Viyerelu23333 @NickKing24 @101polarbears Try it out now :)

**Comment by RichtXO** [comment]
Closing since #506

**Pull request closed without merging**
