### PR TITLE
Update Spring 2021 csv

### PR DESCRIPTION
**Pull request by 123joshuawu**
rpi_data/spring-2021.csv | 2455 ----------------------------------------------
 1 file changed, 2455 deletions(-)

### CODE REVIEW

**Comment by marchdan** [comment]
@123joshuawu Do we know why this PR is asking to delete spring-2021.csv?

**Comment by 123joshuawu** [comment]
@marchdan no clue, will investigate

**Comment by marchdan** [comment]
I can't seem to troubleshoot on Windows, I can also look into it when I can get to Linux

**Comment by marchdan** [comment]
Foud it will patch now

**Comment by marchdan** [comment]
@123joshuawu fixed in #334

**Comment by marchdan** [comment]
This can be closed, and the one today should finish fixing the issue

**Comment by 123joshuawu** [comment]
Ye just waiting on the new update to roll in

**Pull request closed without merging**
