### PR TITLE
Professor Page

### LINKED ISSUE #687: Feature Request — Professor Page
**Job**
Create a page to browse professors and get contact info

**Describe a possible solution**
Create a new page under src/web/src/pages

**Context**
Will use info from web-scraping team

### PR DESCRIPTION
**Pull request by ragar3**
**Issue**

> closes #687

**Database Changes/Migrations**

> none

**Test Modifications**

> none

**Test Procedure**

> none

**Photos**

> currently none due to issues with docker; hopefully will have them soon

**Additional Info**

> currently uses a manually added Professors.json file in src/pages. should eventually use most recent info from web scraper.

### CODE REVIEW

**Review by zhengw5 — APPROVED** [review]
The page looks great I did not find any issues with the page, but when you sort the professors by department, some of the departnames are centered, while others are left-aligned. Like Electrical, Computer, and Systems Engineering is centered, but core engineering is not. Also this may just be my preference, but I think the professors should have their last names first then first name.

**Review by jonha1 — DISMISSED** [review]
feature is great, hopefully, we can expand upon this in the feature and everything works

**Review by mlammon11 — CHANGES_REQUESTED** [review]
Feature looks great and allows users to get more info on professors. However, when listing by department, if I click on a professor, then hit the back arrow; the list goes back to alphabetical not department. If you could change this, that would be great.

**Review by jonha1 — DISMISSED** [review]
Love the new changes, looks good

**Comment by doinglin** [comment]
Everything looks fine to me, except minor bug in web scrapping. I will create a separate issue for that.

**Review by doinglin — DISMISSED** [review]
Everything looks fine to me, except minor bug in web scrapping. I will create a separate issue for that.

**Review by aruan20 — CHANGES_REQUESTED** [review]
The new page looks great! There's just a department title I saw that I think should be the position title and not the department.
Screenshot 2023-07-25 at 2 06 07 PM

**Review by aruan20 — APPROVED** [review]
looks good

**Review by doinglin — APPROVED** [review]

**Pull request merged**
