### PR TITLE
Animated collapse

### PR DESCRIPTION
**Pull request by skyjune0824**
**Issue**

# 622

**Photos**
cl1
cl2

**Additional Info**

Collapse button no animated!

Also, the sidebar is animated.

### CODE REVIEW

**Review by mlammon11 — CHANGES_REQUESTED** [review]
The collapse works well and is a great addition to the website in order to view the schedule better. However the whole header section with explore, pathways, and semester buttons are all unclickable when the side bar is open. Besides this everything looks good.

**Comment by skyjune0824** [comment]
> The collapse works well and is a great addition to the website in order to view the schedule better. However the whole header section with explore, pathways, and semester buttons are all unclickable when the side bar is open. Besides this everything looks good.

Thank you for pointing out, I did fix that problem now!

**Comment by jonha1** [comment]
Love the feature and how useful it is but when it is in dark mode, the arrows to pull out that tab are difficult to see. You can make it a different color maybe blue. It feels like there is a slight delay when closing and opening the tab unless that is intended.

**Comment by skyjune0824** [comment]
Fixed the color, followed by the scheme. It is clearly visible when dark mode is on now.
Also, for the delay when opening, it is mainly because loading time of course selection is relatively long. I can't do anything with it right now, so might consider to change the data structure later.

**Review by zhangn7 — DISMISSED** [review]
I tested what reviewers said previously about the bugs and I can add courses while opening the tab, and the animated collapse button also looks great in dark mode. It is noticeable in light and dark modes.

**Review by mlammon11 — CHANGES_REQUESTED** [review]
Changes from before were mended. However, I see that the color of the course list on light mode is blue, which is a bit hard on the eyes, maybe change it back to black like it currently is. Additionally, I believe that the default action of clicking on the schedule tab is to have the course search on the left instead of automatically closing it.

**Comment by charleschae12** [comment]
Looks GOOOD!

**Review by charleschae12 — DISMISSED** [review]
Looks GOOD.

**Comment by skyjune0824** [comment]
Finalized animation, and color scheme.
It looks fine now :)

캡처

**Review by mlammon11 — APPROVED** [review]
Changes were mended, everything looks great and is functional to the user. Good job

**Review by chavab0809 — DISMISSED** [review]
Just looked through all the change requests and verified that they all work now. Everything looks good!

**Comment by skyjune0824** [comment]
Re-review requested because of master -> this merge to avoid some issues

**Review by zhengw5 — APPROVED** [review]
I just tested this function and everything works great. The feature is really practical and nice for the users and looks great.

**Review by DarknessUnder — APPROVED** [review]

**Pull request merged**
