### PR TITLE
More Info in Schedule Events

### PR DESCRIPTION
**Pull request by Viyerelu23333**
**Issue**
Related to #449

**Database Changes/Migrations**
Added `session_type` and `instructor` to `course_session`.

**Test Modifications**
No.  Columns in `course_session` table do not have any unit test.

**Test Procedure**
- Add some courses, and there will be simplified information in the scheduler (course code, session type and location).
- Click on the schedule event should show the detailed information (course name, instructor, time period, CRN, etc.).
- Click on the course link should redirect to the correct course with correct selected semester.

**Photos**
PC

**Additional Info**
- Feel free to discuss the approaches of displaying overflowed info in Schedule Events.
- ~~The popover cannot be self-dismissed when clicking to other schedule events, maybe modal should be used here?~~ Fixed
- ~~How to let users know that the schedule events are actually clickable?~~ Moved to `hover`
- Now `hsl()` is implemented in `ColorService`, so colors could reduce saturation and luminosity in dark mode.
- The height of scheduler changed to `80vh` to fill the gap at the bottom.
- Added a new cookie `selectedSemester` to hold the state between refreshes.

### CODE REVIEW

**Comment by EthanTuttle** [comment]
Maybe the class type should go lower? Based on that issue #449 we should keep the higher priority information towards the top. I'm not sure if the class type is as important as some of the things below it like professor

**Comment by marchdan** [comment]
@RichtXO Do we have temp deploy's disabled? I'd love to review this, but there is no temp deploy

**Comment by RichtXO** [comment]
@marchdan ye unfortunately. I'm still in a process of replacing the temp deploy with a staging server. Almost done with that!

**Comment by marchdan** [comment]
Also, how does the work done here effect #470?

**Comment by Viyerelu23333** [comment]
> Also, how does the work done here effect #470?

@marchdan They are compatible except one of the branches needs to update to a newer alembic migration, depending on which comes first to the master branch...  I guess.

**Comment by marchdan** [comment]
> > Also, how does the work done here effect #470?
> 
> 
> 
> @marchdan They are compatible except one of the branches needs to update to a newer alembic migration, depending on which comes first to the master branch...  I guess.

I'd say since #470 seems to be a stale PR atm, I'd say that once this PR is completed and merged, someone should update/fix 470 as needed if not finish it.

**Comment by Viyerelu23333** [comment]
> > Well... fixed in a brutal-force way.  Back button still returns to the default semester :)
> 
> Strange, when someone navigates to the regular site, it should automatically navigate to selected semester... (Unless that's now how it's implemented and refreshing goes back to default semester @RichtXO ?)

@marchdan 
I think there was a cookie that stores the current semester...  Might be related to #425?

**Comment by marchdan** [comment]
> > > Well... fixed in a brutal-force way.  Back button still returns to the default semester :)
> 
> > 
> 
> > Strange, when someone navigates to the regular site, it should automatically navigate to selected semester... (Unless that's now how it's implemented and refreshing goes back to default semester @RichtXO ?)
> 
> 
> 
> @marchdan 
> 
> I think there was a cookie that stores the current semester...  Might be related to #425?  

That's how I originally implemented it I think, but I thought it was changed since then? If it's in a cookie than I would think it should be a rather easy fix?

**Comment by marchdan** [comment]
> @marchdan @RichtXO Well... fixed in a brutal-force way. Back button still returns to the default semester :)

This is still happening, but things are otherwise good. Are we approving and making a bug issue for this? Or do we have a fix for it?

**Comment by marchdan** [comment]
@RichtXO @Viyerelu23333 I would love to get this fully approved so we can fully check the UI of #506, any thoughts on the issue of going backward in Explorer? (Issue also occurs if you navigate on a pre-req link FYI)

**Comment by Viyerelu23333** [comment]
> I would love to get this approved so we can merge and fully check the UI of #506, any thoughts on the issue of going backward in Explorer? (Issue also occurs if you navigate on a pre-req link FYI)

@marchdan 
This issue deserves a better solution, just like before.  How about reverting the last two commits and having a new issue of it?

**Comment by marchdan** [comment]
@Viyerelu23333 I still need to go in and properly test this PR in its current state. But if y'all are looking to have these finished by the weekend, the current state of the PR works for the relevant functionality. You can get to the right course from the schedule. It would be nice to have prerequisite links work too, but it's better to have it partly working than not working.

**Comment by Viyerelu23333** [comment]
> I still need to go in and properly test this PR in its current state. But if y'all are looking to have these finished by the weekend, the current state of the PR works for the relevant functionality. You can get to the right course from the schedule. It would be nice to have prerequisite links work too, but it's better to have it partly working than not working.

@marchdan  Sorry if I am wrong, I have no experience to the VueX...
It seems the states from VueX cannot be preserved when refreshing the page. And I am not sure if the backend API could read the VueX states.  We probably need a method to store the `selectedSemester` into some persistent storage like local (session) storage or cookies.

**Comment by marchdan** [comment]
> > I still need to go in and properly test this PR in its current state. But if y'all are looking to have these finished by the weekend, the current state of the PR works for the relevant functionality. You can get to the right course from the schedule. It would be nice to have prerequisite links work too, but it's better to have it partly working than not working.
> 
> 
> 
> @marchdan  Sorry if I am wrong, I have no experience to the VueX...
> 
> It seems the states from VueX cannot be preserved when refreshing the page. And I am not sure if the backend API could read the VueX states.  We probably need a method to store the `selectedSemester` into some persistent storage like local (session) storage or cookies.  

I am still confused as to when it was removed from cookies, lol.

**Comment by Viyerelu23333** [comment]
@marchdan 
Now the cookie is back :)

**Review by RichtXO — APPROVED** [review]

**Pull request merged**
