### PR TITLE
Professor names + emails on individual course pages

### LINKED ISSUE #381: Feature Request — Course Info to Class Website
**Job**
Using the Course Info page as the class website 

**Describe a possible solution**
Every class has a particular website which has links and all. We can populate the course info page with prof's email as well as their OH and the link to their class website. It would make contacting the professor easier!
**Context**

### PR DESCRIPTION
**Pull request by i-am-david-liu**
**Issue**
> Closes #381

Note: doesn't fully close #381, as it will only add professor emails and their names, the latter which is unrelated to the issue entirely. Should I make a new issue that's more specific?

**Database Changes/Migrations**
> Adds "course_instructor" and "email" column to .csv

**Photos**

to

**TO DO**
- Display emails for courses with more than one instructor
- Revise test cases

### CODE REVIEW

**Comment by marchdan** [comment]
I see in the description you say it adds professor names. Was that not already being parsed through into the csv? If not the logic to do so should already exist as I know I wrote it.

**Comment by i-am-david-liu** [comment]
> I see in the description you say it adds professor names. Was that not already being parsed through into the csv? If not the logic to do so should already exist as I know I wrote it.

Sorry for inactivity; tail end of Arch is a doozy. It is true that the professor names are already in the csv, so that should be reasonably "easy" to do. I already managed to get emails working for most courses with one instructor, the next part is figuring out how RCOS passes data from the table to frontend. Any advice?

**Comment by marchdan** [comment]
> Sorry for inactivity; tail end of Arch is a doozy. It is true that the professor names are already in the csv, so that should be reasonably "easy" to do. I already managed to get emails working for most courses with one instructor, the next part is figuring out how RCOS passes data from the table to frontend. Any advice?

That happens in the API layer. I am linking some helpful files below:
(Backend db)[https://github.com/YACS-RCOS/yacs.n/tree/master/src/api/db] - Look at classinfo & courses
(Main API)[https://github.com/YACS-RCOS/yacs.n/blob/98e50f880d09c1775ba526173ef59929a045e5c7/src/api/app.py]
(Data tables)[https://github.com/YACS-RCOS/yacs.n/tree/master/src/api/tables] - Look at course
(YACS service)[https://github.com/YACS-RCOS/yacs.n/blob/98e50f880d09c1775ba526173ef59929a045e5c7/src/web/src/services/YacsService.js]

These are various locations to either help see how data is routed, or that would need additions to grab the data.
In rough terms, the route goes: CSV -> Tables/db -> API -> service -> Frontend

**Comment by i-am-david-liu** [comment]
I'm getting an error where `column "course_instructor" of relation "course" does not exist`, even when I declared the column in course.py. Any idea why this happens?

**Comment by marchdan** [comment]
> I'm getting an error where `column "course_instructor" of relation "course" does not exist`, even when I declared the column in course.py. Any idea why this happens?

When making changes to the tables you need to make sure you run the dev_build.sh script before your start script

**Comment by i-am-david-liu** [comment]
> When making changes to the tables you need to make sure you run the dev_build.sh script before your start script

I followed the procedure:
`dev-stop.sh`
`dev-build.sh`
`dev-start.sh`
Tables don't seem to be updating. I'm sure of this because I commented out existing columns and YACS still reads them.

**Comment by marchdan** [comment]
@i-am-david-liu And this error is being thrown from the code currently on this branch? I can pull it locally and see what I can do.

**Comment by marchdan** [comment]
Need to fix issue with backend tests (It might just be adding test to have coverage of newly added table data) before it can populate a temp deploy to allow proper testing.

**Pull request closed without merging**
